[package]
name = "is_pcr_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
memchr = { version = "2.7.5" }
clap = { version = "4.5.41", features = ["derive"] }
bio = { version = "2.3.0" }
log = { version = "0.4.27" }
simple_logger = { version = "5.0.0" }
indicatif = { version = "0.18.0" }
